[build]
# rustflags = ["-Zlocation-detail=none"]
target = ["x86_64-unknown-linux-musl"]
# rustc-wrapper = "sccache"

[target.x86_64-unknown-linux-musl]
linker = "clang"
rustflags = ["-C", "link-arg=--ld-path=wild"]
